name: Pages
on:
 push:
   branches:
    - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Set Up Python 3.10.8
     uses: actions/setup-python@v3
     with:
       python-version: 3.10.8   
   - uses: actions/checkout@master
     with:
       fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
   - name: Build and Commit
     uses: iSOLveIT/mkdocs-notes@main
     with:
       config_file_path: mkdocs.yml 
   - name: Push changes
     uses: ad-m/github-push-action@master
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       branch: site
